apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: twinkle-ns
  labels:
    app: {{ .Chart.Name }}
    project: twinkle-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        project: twinkle-chat
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: my-local-registry.example.com:5000/{{ .Chart.Name }}:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /chat-app
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 600
          livenessProbe:
            httpGet:
              path: /chat-app
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 600
          env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: app_key
          - name: BACKEND_CHAT_API_URL
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: backend_chat_api_url
          - name: NEXTAUTH_URL
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: nextauth_url
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: nextauth_secret
          - name: NEXTAUTH_TOKEN_MAXAGE
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: next_auth_token_maxage
          - name: NEXTAUTH_TOKEN_UPDATEAGE
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: next_auth_token_updateage