apiVersion: v1
kind: Service
metadata:
  name: nextjs-chat-service
  namespace: twinkle-ns
spec:
  selector:
    app: nextjs-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
